### ISSUE TITLE
java.lang.IllegalStateException when following usage instructions in README

### ISSUE THREAD

**Issue by wolfskaempf** [protomaps/basemaps#115]
# Steps for reproduction
Environment: Running inside this container image `docker.io/maven:3-eclipse-temurin-17`.

1. Clone this repository.

```shell
git clone git@github.com:protomaps/basemaps.git
```
2. change to the `tiles` directory, download dependencies and compile the JAR:

```shell
cd basemaps/tiles
mvn clean package
```
3. Download and generate `monaco.pmtiles` in the current directory:

```shell
java -jar target/*-with-deps.jar --download --force --area=monaco
```

# Observed behaviour
The process stops with the following exception.

```
Exception in thread "main" java.lang.IllegalStateException: Error getting size of https://download.geofabrik.de/europe/monaco-latest.osm.pbf
        at com.onthegomap.planetiler.util.Downloader.run(Downloader.java:186)
        at com.onthegomap.planetiler.Planetiler.download(Planetiler.java:903)
        at com.onthegomap.planetiler.Planetiler.run(Planetiler.java:716)
        at com.protomaps.basemap.Basemap.run(Basemap.java:145)
        at com.protomaps.basemap.Basemap.main(Basemap.java:108)
Caused by: java.util.concurrent.TimeoutException
        at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
        at com.onthegomap.planetiler.util.Downloader.run(Downloader.java:180)
        ... 4 more
```

# Expected behaviour
A `monaco.pmtiles` file is generated.

# Thank you
Thank you for making protomaps! I'm so far really enjoying building maps with it with the precompiled `.pmtiles` files. I'm currently working on making my own tilesets using this repository.

**Comment by bdon** [comment]
Can you reproduce this now? It looks like an intermittent issue with the PBF download source. 

Also, is there a particular reason you need to inside Docker instead of a JVM on the host machine? Does your container have network access?
